# Generated by Django 6.0.6 on 2026-06-12 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_location", models.CharField(max_length=255)),
                ("pickup_location", models.CharField(max_length=255)),
                ("dropoff_location", models.CharField(max_length=255)),
                ("cycle_used_hours", models.FloatField()),
                ("distance_miles", models.FloatField()),
                ("duration_hours", models.FloatField()),
                ("fuel_stops", models.IntegerField(default=0)),
                ("rest_stops", models.IntegerField(default=0)),
                ("trip_days", models.IntegerField(default=1)),
                ("trip_status", models.CharField(max_length=50)),
                ("route_data", models.JSONField(blank=True, null=True)),
                ("hos_data", models.JSONField(blank=True, null=True)),
                ("timeline_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "current_location",
                            "pickup_location",
                            "dropoff_location",
                            "cycle_used_hours",
                        ),
                        name="unique_trip",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ELDLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("carrier_name", models.CharField(max_length=255)),
                ("truck_number", models.CharField(max_length=100)),
                (
                    "trailer_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "shipping_document",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("odometer_start", models.IntegerField()),
                ("eld_data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eld_logs",
                        to="trips.trip",
                    ),
                ),
            ],
        ),
    ]
